import type { Job, Placement } from "./parse-xlsx";

/**
 * Load jobs from the static /jobs.csv (generated by data/convert.py).
 */
export async function loadJobs(): Promise<Job[]> {
  const res = await fetch("/jobs.csv");
  const text = await res.text();
  return parseCsv(text);
}

function parseCsv(text: string): Job[] {
  const lines = text.split("\n").filter((l) => l.trim() !== "");
  if (lines.length < 2) return [];

  const headers = splitCsvLine(lines[0]);
  const col = (name: string) => headers.indexOf(name);

  const jobs: Job[] = [];
  for (let i = 1; i < lines.length; i++) {
    const vals = splitCsvLine(lines[i]);
    const get = (name: string) => {
      const idx = col(name);
      return idx >= 0 && idx < vals.length ? vals[idx] : "";
    };

    const placement = (n: number): Placement => ({
      site: get(`p${n}_site`) || "None",
      speciality: get(`p${n}_speciality`) || "None",
      ...(n >= 4 ? { description: get(`p${n}_description`) || "None" } : {}),
    });

    jobs.push({
      id: crypto.randomUUID(),
      programme_title: get("programme_title"),
      region: get("region") as Job["region"],
      placement_1: placement(1),
      placement_2: placement(2),
      placement_3: placement(3),
      placement_4: placement(4),
      placement_5: placement(5),
      placement_6: placement(6),
    });
  }

  return jobs;
}

/** Simple CSV line splitter that handles quoted fields. */
function splitCsvLine(line: string): string[] {
  const result: string[] = [];
  let current = "";
  let inQuotes = false;

  for (let i = 0; i < line.length; i++) {
    const ch = line[i];
    if (inQuotes) {
      if (ch === '"' && line[i + 1] === '"') {
        current += '"';
        i++;
      } else if (ch === '"') {
        inQuotes = false;
      } else {
        current += ch;
      }
    } else if (ch === '"') {
      inQuotes = true;
    } else if (ch === ",") {
      result.push(current);
      current = "";
    } else {
      current += ch;
    }
  }
  result.push(current);
  return result;
}
